// frontend/src/app/features/auth/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, ActivatedRoute, RouterLink } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  loginForm: FormGroup;
  loading = false;
  error = '';
  returnUrl: string = '/dashboard';

  constructor(
    private formBuilder: FormBuilder,
    private route: ActivatedRoute,
    private router: Router,
    private authService: AuthService
  ) {
    this.loginForm = this.formBuilder.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]]
    });
  }

  ngOnInit() {
    // Obtener URL de retorno desde los parámetros de la ruta o usar por defecto '/dashboard'
    this.returnUrl = this.route.snapshot.queryParams['returnUrl'] || '/dashboard';
  }

  // Getter para acceso fácil a los campos del formulario
  get f() { return this.loginForm.controls; }

  onSubmit() {
    // Detener si el formulario es inválido
    if (this.loginForm.invalid) {
      return;
    }

    this.loading = true;
    this.error = '';

    this.authService.login(
      this.f['email'].value,
      this.f['password'].value
    ).subscribe({
      next: () => {
        this.router.navigate([this.returnUrl]);
      },
      error: error => {
        this.error = error.message || 'Error al iniciar sesión';
        this.loading = false;
      }
    });
  }
} 
<div class="auth-container">
  <div class="form-container">
    <h1 class="page-title-login">GYM TRACK</h1>
    <p class="page-subtitle-login">Tu compañero de entrenamiento</p>
    
    <div *ngIf="error" class="error-message">
      {{ error }}
    </div>
    
    <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="email" class="form-label">
          Email
        </label>
        <input 
          type="email" 
          formControlName="email" 
          class="form-input" 
          [ngClass]="{ 'border-error': f['email'].touched && f['email'].errors }" 
          placeholder="tu@email.com"
        />
        <div *ngIf="f['email'].touched && f['email'].errors" class="text-error text-sm mt-1">
          <div *ngIf="f['email'].errors['required']">Email es requerido</div>
          <div *ngIf="f['email'].errors['email']">Ingresa un email válido</div>
        </div>
      </div>
      
      <div class="form-group">
        <label for="password" class="form-label">
          Contraseña
        </label>
        <input 
          type="password" 
          formControlName="password" 
          class="form-input" 
          [ngClass]="{ 'border-error': f['password'].touched && f['password'].errors }" 
          placeholder="••••••••"
        />
        <div *ngIf="f['password'].touched && f['password'].errors" class="text-error text-sm mt-1">
          <div *ngIf="f['password'].errors['required']">Contraseña es requerida</div>
          <div *ngIf="f['password'].errors['minlength']">La contraseña debe tener al menos 6 caracteres</div>
        </div>
      </div>
      
      <div class="form-group">
        <button [disabled]="loading || loginForm.invalid" class="primary-button">
          <span *ngIf="loading" class="spinner"></span>
          Iniciar Sesión
        </button>
      </div>
      
      <div class="auth-link">
        <p>¿No tienes una cuenta? <a routerLink="/register">Regístrate aquí</a></p>
      </div>
    </form>
  </div>
</div>

// frontend/src/app/login/page.tsx
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useAuth } from '@/context/AuthContext';
import './login.css';

export default function LoginPage() {
  const [formData, setFormData] = useState({
    email: '',
    password: '',
  });
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const { login } = useAuth();

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setIsLoading(true);

    try {
      await login(formData.email, formData.password);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="auth-container">
      <div className="form-container">
        <h1 className="page-title">GYM TRACK</h1>
        <p className="page-subtitle">Tu compañero de entrenamiento</p>

        {error && (
          <div className="error-message">
            <p>{error}</p>
          </div>
        )}

        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="email" className="form-label">
              Email
            </label>
            <input
              id="email"
              name="email"
              type="email"
              required
              className="form-input"
              value={formData.email}
              onChange={handleChange}
              disabled={isLoading}
              placeholder="tu@email.com"
            />
          </div>

          <div className="form-group">
            <label htmlFor="password" className="form-label">
              Contraseña
            </label>
            <input
              id="password"
              name="password"
              type="password"
              required
              className="form-input"
              value={formData.password}
              onChange={handleChange}
              disabled={isLoading}
              placeholder="••••••••"
            />
          </div>

          <button
            type="submit"
            className="primary-button"
            disabled={isLoading}
          >
            {isLoading ? (
              <>
                <span className="spinner">⭮</span>
                Iniciando sesión...
              </>
            ) : 'Iniciar Sesión'
            }
          </button>
        </form>

        <div className="auth-link">
          <p>
            ¿No tienes una cuenta?{' '}
            <Link href="/register">
              Regístrate aquí
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
