// frontend/src/app/features/workouts/workouts.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, ActivatedRoute } from '@angular/router';
import { Workout } from '../../core/models/workout.model';
import { AuthService } from '../../core/services/auth.service';
import { WorkoutService } from '../../core/services/workout.service';
import { WorkoutFormComponent } from './workout-form/workout-form.component';
import { ToastrService } from 'ngx-toastr';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-workouts',
  standalone: true,
  imports: [CommonModule, WorkoutFormComponent],
  templateUrl: './workouts.component.html',
  styleUrls: ['./workouts.component.scss']
})
export class WorkoutsComponent implements OnInit {
  workouts: Workout[] = [];
  loading = true;
  showForm = false;
  editWorkout: Workout | null = null;

  constructor(
    public router: Router, // Cambiado a público para acceder desde la plantilla
    private route: ActivatedRoute,
    private authService: AuthService,
    private workoutService: WorkoutService,
    private toastr: ToastrService
  ) {}

  ngOnInit(): void {
    this.fetchWorkouts();
    
    // Manejar parámetros de URL
    this.route.queryParams.subscribe(params => {
      const newParam = params['new'];
      const idParam = params['id'];
      
      if (newParam === 'true') {
        this.showForm = true;
        this.editWorkout = null;
      } else if (idParam) {
        this.fetchSingleWorkout(idParam);
      }
    });
  }

  fetchWorkouts(): void {
    this.loading = true;
    this.workoutService.getWorkouts().subscribe({
      next: (workouts) => {
        this.workouts = workouts;
        this.loading = false;
      },
      error: (error) => {
        console.error('Error al cargar entrenamientos:', error);
        this.toastr.error('Error al cargar los entrenamientos');
        this.loading = false;
      }
    });
  }

  fetchSingleWorkout(id: string): void {
    this.loading = true;
    this.workoutService.getWorkout(id).subscribe({
      next: (workout) => {
        this.editWorkout = workout;
        this.showForm = true;
        this.loading = false;
      },
      error: (error) => {
        console.error('Error al cargar entrenamiento:', error);
        this.toastr.error('Error al cargar el entrenamiento');
        this.loading = false;
      }
    });
  }

  handleCreateWorkout(workoutData: any): void {
    this.workoutService.createWorkout(workoutData).subscribe({
      next: (workout) => {
        this.toastr.success('Entrenamiento creado correctamente');
        this.showForm = false;
        this.fetchWorkouts();
      },
      error: (error) => {
        console.error('Error al crear entrenamiento:', error);
        this.toastr.error('Error al crear el entrenamiento');
      }
    });
  }

  handleUpdateWorkout(workoutData: any): void {
    if (!this.editWorkout?.id) return;
    
    this.workoutService.updateWorkout(this.editWorkout.id, workoutData).subscribe({
      next: (workout) => {
        this.toastr.success('Entrenamiento actualizado correctamente');
        this.showForm = false;
        this.editWorkout = null;
        this.fetchWorkouts();
      },
      error: (error) => {
        console.error('Error al actualizar entrenamiento:', error);
        this.toastr.error('Error al actualizar el entrenamiento');
      }
    });
  }

  handleDeleteWorkout(id: string): void {
    Swal.fire({
      title: '¿Estás seguro?',
      text: 'No podrás revertir esta acción',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#22c55e',
      cancelButtonColor: '#ef4444',
      confirmButtonText: 'Sí, eliminar',
      cancelButtonText: 'Cancelar'
    }).then((result) => {
      if (result.isConfirmed) {
        this.workoutService.deleteWorkout(id).subscribe({
          next: () => {
            this.toastr.success('Entrenamiento eliminado correctamente');
            this.fetchWorkouts();
          },
          error: (error) => {
            console.error('Error al eliminar entrenamiento:', error);
            this.toastr.error('Error al eliminar el entrenamiento');
          }
        });
      }
    });
  }

  handleViewWorkout(workout: Workout): void {
    this.router.navigate(['/workouts', workout.id]);
  }

  handleNewWorkout(): void {
    this.router.navigate(['/workouts'], { queryParams: { new: true } });
  }

  handleFormCancel(): void {
    this.showForm = false;
    this.editWorkout = null;
    this.router.navigate(['/workouts']);
  }

  handleFormSubmit(workoutData: any): void {
    if (this.editWorkout) {
      this.handleUpdateWorkout(workoutData);
    } else {
      this.handleCreateWorkout(workoutData);
    }
  }

  // Agrupar ejercicios por día
  getExercisesByDay(workout: Workout): string[] {
    const days = new Set(workout.exercises.map(exercise => exercise.day));
    return Array.from(days);
  }
} 
<div class="workouts-container">
  <div class="flex justify-between items-center mb-6">
    <h1 class="workouts-title">Mis Entrenamientos</h1>
    <button 
      *ngIf="!showForm"
      class="primary-button"
      (click)="handleNewWorkout()"
    >
      <i class="fas fa-plus"></i>
      Nuevo
    </button>
  </div>

  <div *ngIf="loading" class="flex justify-center items-center h-64">
    <div class="spinner"></div>
  </div>

  <div *ngIf="!loading && !showForm" class="workouts-list">
    <div *ngIf="workouts.length === 0" class="empty-state">
      <p>No hay entrenamientos registrados.</p>
      <p>¡Comienza creando uno nuevo!</p>
      <button 
        class="primary-button mt-4"
        (click)="handleNewWorkout()"
      >
        Crear mi primer entrenamiento
      </button>
    </div>

    <div *ngFor="let workout of workouts" class="workout-card">
      <div class="workout-card-header">
        <h3 class="workout-card-title">{{ workout.title }}</h3>
      </div>

      <div class="workout-card-body">
        <div class="workout-stats">
          <div class="workout-stat">
            <span class="workout-stat-label">Ejercicios</span>
            <span class="workout-stat-value">{{ workout.exercises.length }}</span>
          </div>
          <div class="workout-stat">
            <span class="workout-stat-label">Días</span>
            <span class="workout-stat-value">{{ getExercisesByDay(workout).length }}</span>
          </div>
        </div>

        <div class="workout-days">
          <span *ngFor="let day of getExercisesByDay(workout)" class="workout-day-tag">
            {{ day }}
          </span>
        </div>

        <div *ngIf="workout.notes" class="workout-notes">
          <p>{{ workout.notes }}</p>
        </div>
      </div>

      <div class="workout-card-footer">
        <button 
          class="workout-action-button view"
          (click)="handleViewWorkout(workout)"
        >
          <i class="fas fa-edit"></i>
        </button>
        <button 
          class="workout-action-button progress"
          (click)="router.navigate(['/workouts', workout.id, 'progress'])"
        >
          <i class="fas fa-chart-line"></i>
        </button>
        <button 
          class="workout-action-button delete"
          (click)="handleDeleteWorkout(workout.id)"
        >
          <i class="fas fa-trash"></i>
        </button>
      </div>
    </div>
  </div>

  <!-- Formulario de entrenamiento -->
  <div *ngIf="showForm">
    <app-workout-form
      [initialData]="editWorkout || undefined"
      (onSubmit)="handleFormSubmit($event)"
      (onCancel)="handleFormCancel()"
    ></app-workout-form>
  </div>
</div>

// frontend/src/app/workouts/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import DashboardLayout from '@/components/DashboardLayout';
import WorkoutForm from '@/components/WorkoutForm';
import { Workout } from '@/types';
import './workouts.css';

export default function WorkoutsPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [workouts, setWorkouts] = useState<Workout[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [editWorkout, setEditWorkout] = useState<Workout | null>(null);

  useEffect(() => {
    fetchWorkouts();
    
    // Manejar parámetros de URL
    const newParam = searchParams.get('new');
    const idParam = searchParams.get('id');
    
    if (newParam === 'true') {
      setShowForm(true);
      setEditWorkout(null);
    } else if (idParam) {
      fetchSingleWorkout(idParam);
    }
  }, [searchParams]);

  const fetchWorkouts = async () => {
    try {
      const token = localStorage.getItem('token');
      const res = await fetch('http://localhost:5000/api/workouts', {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      if (!res.ok) {
        throw new Error('Error al obtener los entrenamientos');
      }

      const data = await res.json();
      setWorkouts(data);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const fetchSingleWorkout = async (id: string) => {
    try {
      setLoading(true);
      const token = localStorage.getItem('token');
      const res = await fetch(`http://localhost:5000/api/workouts/${id}`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      if (!res.ok) {
        throw new Error('Error al obtener el entrenamiento');
      }

      const workout = await res.json();
      setEditWorkout(workout);
      setShowForm(true);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleCreateWorkout = async (workoutData: Omit<Workout, 'id' | 'completed'>) => {
    try {
      setLoading(true);
      const token = localStorage.getItem('token');
      const res = await fetch('http://localhost:5000/api/workouts', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(workoutData),
      });

      if (!res.ok) {
        const data = await res.json();
        if (data.errors) {
          // Si hay errores de validación, mostrarlos
          const errorMessages = data.errors.map((err: any) => err.msg).join(', ');
          throw new Error(`Error al crear el entrenamiento: ${errorMessages}`);
        }
        throw new Error(data.message || 'Error al crear el entrenamiento');
      }

      await fetchWorkouts();
      setShowForm(false);
      // Limpiar parámetros de URL
      router.push('/workouts');
    } catch (err: any) {
      setError(err.message);
      console.error('Error al crear el entrenamiento:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleUpdateWorkout = async (workoutData: Omit<Workout, 'id' | 'completed'>) => {
    if (!editWorkout) return;

    try {
      setLoading(true);
      const token = localStorage.getItem('token');
      const res = await fetch(`http://localhost:5000/api/workouts/${editWorkout.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(workoutData),
      });

      if (!res.ok) {
        const data = await res.json();
        if (data.errors) {
          // Si hay errores de validación, mostrarlos
          const errorMessages = data.errors.map((err: any) => err.msg).join(', ');
          throw new Error(`Error al actualizar el entrenamiento: ${errorMessages}`);
        }
        throw new Error(data.message || 'Error al actualizar el entrenamiento');
      }

      await fetchWorkouts();
      setEditWorkout(null);
      setShowForm(false);
      // Limpiar parámetros de URL
      router.push('/workouts');
    } catch (err: any) {
      setError(err.message);
      console.error('Error al actualizar el entrenamiento:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteWorkout = async (id: string) => {
    if (!confirm('¿Estás seguro de que deseas eliminar este entrenamiento?')) {
      return;
    }

    try {
      setLoading(true);
      const token = localStorage.getItem('token');
      const res = await fetch(`http://localhost:5000/api/workouts/${id}`, {
        method: 'DELETE',
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      if (!res.ok) {
        throw new Error('Error al eliminar el entrenamiento');
      }

      await fetchWorkouts();
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleToggleComplete = async (workout: Workout) => {
    try {
      setLoading(true);
      const token = localStorage.getItem('token');
      const res = await fetch(`http://localhost:5000/api/workouts/${workout.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          completed: !workout.completed
        }),
      });

      if (!res.ok) {
        throw new Error('Error al actualizar el estado del entrenamiento');
      }

      await fetchWorkouts();
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleViewWorkout = (workout: Workout) => {
    router.push(`/workouts/${workout.id}`);
  };

  const handleNewWorkout = () => {
    router.push('/workouts?new=true');
  };

  const handleFormCancel = () => {
    setShowForm(false);
    setEditWorkout(null);
    // Limpiar parámetros de URL
    router.push('/workouts');
  };

  const handleFormSubmit = (workoutData: Omit<Workout, 'id' | 'completed'>) => {
    if (editWorkout) {
      handleUpdateWorkout(workoutData);
    } else {
      handleCreateWorkout(workoutData);
    }
  };

  // Agrupar ejercicios por día
  const getExercisesByDay = (workout: Workout) => {
    const days = new Set(workout.exercises.map(exercise => exercise.day));
    return Array.from(days);
  };

  if (loading && !showForm) {
    return (
      <DashboardLayout>
        <div className="flex justify-center items-center h-64">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
        </div>
      </DashboardLayout>
    );
  }

  if (showForm) {
    return (
      <DashboardLayout>
        <WorkoutForm 
          onSubmit={handleFormSubmit} 
          onCancel={handleFormCancel} 
          initialData={editWorkout || undefined}
        />
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout>
      <div className="workouts-container">
        <div className="flex justify-between items-center mb-6">
          <h1 className="workouts-title">Mis Entrenamientos</h1>
          <button 
            className="primary-button"
            onClick={handleNewWorkout}
          >
            Nuevo Entrenamiento
          </button>
        </div>

        {error && (
          <div className="error-message">
            {error}
          </div>
        )}

        <div className="workouts-list">
          {workouts.length === 0 ? (
            <div className="empty-state">
              <p>No hay entrenamientos registrados.</p>
              <p>¡Comienza creando uno nuevo!</p>
              <button 
                className="primary-button mt-4"
                onClick={handleNewWorkout}
              >
                Crear mi primer entrenamiento
              </button>
            </div>
          ) : (
            workouts.map((workout) => (
              <div
                key={workout.id}
                className="workout-card"
              >
                <div className="workout-card-header">
                  <h3 className="workout-card-title">{workout.title}</h3>
                  <span
                    className={`workout-status ${
                      workout.completed ? 'completed' : 'in-progress'
                    }`}
                  >
                    {workout.completed ? 'Completado' : 'En progreso'}
                  </span>
                </div>

                <div className="workout-card-body">
                  <div className="workout-stats">
                    <div className="workout-stat">
                      <span className="workout-stat-label">Ejercicios</span>
                      <span className="workout-stat-value">{workout.exercises.length}</span>
                    </div>
                    <div className="workout-stat">
                      <span className="workout-stat-label">Días</span>
                      <span className="workout-stat-value">{getExercisesByDay(workout).length}</span>
                    </div>
                  </div>

                  <div className="workout-days">
                    {getExercisesByDay(workout).map((day) => (
                      <span key={day} className="workout-day-tag">
                        {day}
                      </span>
                    ))}
                  </div>

                  {workout.notes && (
                    <div className="workout-notes">
                      <p>{workout.notes}</p>
                    </div>
                  )}
                </div>

                <div className="workout-card-footer">
                  <button 
                    className="workout-action-button view"
                    onClick={() => handleViewWorkout(workout)}
                  >
                    Ver detalles
                  </button>
                  <button 
                    className={`workout-action-button ${workout.completed ? 'incomplete' : 'complete'}`}
                    onClick={() => handleToggleComplete(workout)}
                  >
                    {workout.completed ? 'Marcar incompleto' : 'Marcar completado'}
                  </button>
                  <button 
                    className="workout-action-button delete"
                    onClick={() => handleDeleteWorkout(workout.id)}
                  >
                    Eliminar
                  </button>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </DashboardLayout>
  );
}
