// frontend/src/app/features/auth/register/register.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent {
  registerForm: FormGroup;
  loading = false;
  error = '';
  passwordStrength = 0;

  constructor(
    private formBuilder: FormBuilder,
    private router: Router,
    private authService: AuthService
  ) {
    this.registerForm = this.formBuilder.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      confirmPassword: ['', Validators.required]
    }, {
      validator: this.passwordMatchValidator
    });

    // Suscribirse a los cambios en el campo de contraseña para actualizar la fortaleza
    this.registerForm.get('password')?.valueChanges.subscribe(password => {
      this.passwordStrength = this.calculatePasswordStrength(password);
    });
  }

  // Validador personalizado para verificar que las contraseñas coincidan
  passwordMatchValidator(formGroup: FormGroup) {
    const password = formGroup.get('password')?.value;
    const confirmPassword = formGroup.get('confirmPassword')?.value;

    if (password !== confirmPassword) {
      formGroup.get('confirmPassword')?.setErrors({ passwordMismatch: true });
    } else {
      formGroup.get('confirmPassword')?.setErrors(null);
    }
  }

  // Calcular la fortaleza de la contraseña (0-4)
  calculatePasswordStrength(password: string): number {
    if (!password) return 0;
    
    let strength = 0;
    
    // Longitud mínima
    if (password.length >= 8) strength++;
    
    // Contiene letras minúsculas y mayúsculas
    if (/[a-z]/.test(password) && /[A-Z]/.test(password)) strength++;
    
    // Contiene números
    if (/[0-9]/.test(password)) strength++;
    
    // Contiene caracteres especiales
    if (/[^a-zA-Z0-9]/.test(password)) strength++;
    
    return strength;
  }

  // Getter para acceso fácil a los campos del formulario
  get f() { return this.registerForm.controls; }

  onSubmit() {
    // Detener si el formulario es inválido
    if (this.registerForm.invalid) {
      return;
    }

    this.loading = true;
    this.error = '';

    this.authService.register(
      this.f['email'].value,
      this.f['password'].value
    ).subscribe({
      next: () => {
        this.router.navigate(['/dashboard']);
      },
      error: error => {
        this.error = error.message || 'Error al registrar usuario';
        this.loading = false;
      }
    });
  }
} 
<div class="auth-container">
  <div class="form-container">
    <h1 class="page-title-register">GYM TRACK</h1>
    <p class="page-subtitle-register">CREA TU CUENTA</p>
    
    <div *ngIf="error" class="error-message">
      {{ error }}
    </div>
    
    <form [formGroup]="registerForm" (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="email" class="form-label">EMAIL</label>
        <input 
          type="email" 
          formControlName="email" 
          class="form-input" 
          [ngClass]="{ 'border-error': f['email'].touched && f['email'].errors }" 
          placeholder="tu@email.com"
        />
        <div *ngIf="f['email'].touched && f['email'].errors" class="text-error text-sm mt-1">
          <div *ngIf="f['email'].errors['required']">Email es requerido</div>
          <div *ngIf="f['email'].errors['email']">Ingresa un email válido</div>
        </div>
      </div>
      
      <div class="form-group">
        <label for="password" class="form-label">CONTRASEÑA</label>
        <input 
          type="password" 
          formControlName="password" 
          class="form-input" 
          [ngClass]="{ 'border-error': f['password'].touched && f['password'].errors }" 
          placeholder="••••••••"
        />
        <div *ngIf="f['password'].touched && f['password'].errors" class="text-error text-sm mt-1">
          <div *ngIf="f['password'].errors['required']">Contraseña es requerida</div>
          <div *ngIf="f['password'].errors['minlength']">La contraseña debe tener al menos 6 caracteres</div>
        </div>
        
        <div class="password-strength mt-2" *ngIf="f['password'].value">
          <div class="strength-bars flex gap-1 mb-2">
            <div class="strength-bar h-1 flex-1 rounded-sm" 
                [ngClass]="{'bg-red-500': passwordStrength >= 1, 'bg-gray-300': passwordStrength < 1}"></div>
            <div class="strength-bar h-1 flex-1 rounded-sm" 
                [ngClass]="{'bg-yellow-500': passwordStrength >= 2, 'bg-gray-300': passwordStrength < 2}"></div>
            <div class="strength-bar h-1 flex-1 rounded-sm" 
                [ngClass]="{'bg-green-500': passwordStrength >= 3, 'bg-gray-300': passwordStrength < 3}"></div>
            <div class="strength-bar h-1 flex-1 rounded-sm" 
                [ngClass]="{'bg-green-600': passwordStrength >= 4, 'bg-gray-300': passwordStrength < 4}"></div>
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <label for="confirmPassword" class="form-label">CONFIRMAR CONTRASEÑA</label>
        <input 
          type="password" 
          formControlName="confirmPassword" 
          class="form-input" 
          [ngClass]="{ 'border-error': f['confirmPassword'].touched && f['confirmPassword'].errors }" 
          placeholder="••••••••"
        />
        <div *ngIf="f['confirmPassword'].touched && f['confirmPassword'].errors" class="text-error text-sm mt-1">
          <div *ngIf="f['confirmPassword'].errors['required']">Confirmación de contraseña es requerida</div>
          <div *ngIf="f['confirmPassword'].errors['passwordMismatch']">Las contraseñas no coinciden</div>
        </div>
      </div>
      
      <div class="form-group">
        <button [disabled]="loading || registerForm.invalid" class="primary-button">
          <span *ngIf="loading" class="spinner"></span>
          CREAR CUENTA
        </button>
      </div>
      
      <div class="auth-link">
        <p>¿Ya tienes una cuenta? <a routerLink="/login">INICIAR SESIÓN</a></p>
      </div>
    </form>
  </div>
</div>

// frontend/src/app/register/page.tsx
'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useAuth } from '@/context/AuthContext';
import './register.css';

const validatePassword = (password: string) => {
  const checks = {
    length: password.length >= 8,
    uppercase: /[A-Z]/.test(password),
    lowercase: /[a-z]/.test(password),
    number: /[0-9]/.test(password),
    special: /[!@#$%^&*(),.?":{}|<>]/.test(password),
  };
  
  return {
    ...checks,
    score: Object.values(checks).filter(Boolean).length,
  };
};

const validateEmail = (email: string): boolean => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
};

export default function RegisterPage() {
  const [formData, setFormData] = useState({
    email: '',
    password: '',
    confirmPassword: '',
  });
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [passwordStrength, setPasswordStrength] = useState({
    score: 0,
    length: false,
    uppercase: false,
    lowercase: false,
    number: false,
    special: false,
  });
  const { register } = useAuth();

  useEffect(() => {
    setPasswordStrength(validatePassword(formData.password));
  }, [formData.password]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
    setError('');
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    // Validar email
    if (!validateEmail(formData.email)) {
      setError('Por favor, introduce un email válido');
      return;
    }

    // Validar contraseña
    if (passwordStrength.score < 3) {
      setError('La contraseña debe cumplir al menos 3 criterios de seguridad');
      return;
    }

    if (formData.password !== formData.confirmPassword) {
      setError('Las contraseñas no coinciden');
      return;
    }

    setIsLoading(true);

    try {
      await register(formData.email, formData.password);
    } catch (err: any) {
      if (err.message.includes('Ya existe una cuenta')) {
        setError('Ya existe una cuenta con este email');
      } else {
        setError(err.message || 'Error al registrar usuario');
      }
    } finally {
      setIsLoading(false);
    }
  };

  const getPasswordStrengthColor = () => {
    if (passwordStrength.score < 2) return 'bg-red-500';
    if (passwordStrength.score < 4) return 'bg-yellow-500';
    return 'bg-green-500';
  };

  return (
    <div className="auth-container">
      <div className="form-container">
        <h1 className="page-title">GYM TRACK</h1>
        <p className="page-subtitle">Únete a la comunidad</p>

        {error && (
          <div className="error-message">
            <p>{error}</p>
          </div>
        )}

        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="email" className="form-label">
              Email
            </label>
            <input
              id="email"
              name="email"
              type="email"
              required
              className="form-input"
              value={formData.email}
              onChange={handleChange}
              disabled={isLoading}
              placeholder="tu@email.com"
            />
          </div>

          <div className="form-group">
            <label htmlFor="password" className="form-label">
              Contraseña
            </label>
            <input
              id="password"
              name="password"
              type="password"
              required
              className="form-input"
              value={formData.password}
              onChange={handleChange}
              disabled={isLoading}
              placeholder="••••••••"
            />
            <div className="password-strength">
              <div className="strength-bars">
                {[1, 2, 3, 4, 5].map((index) => (
                  <div
                    key={index}
                    className={`strength-bar ${
                      index <= passwordStrength.score ? getPasswordStrengthColor() : 'bg-gray-200'
                    }`}
                  />
                ))}
              </div>
              <ul className="password-requirements">
                <li className={passwordStrength.length ? 'met' : ''}>
                  ✓ Mínimo 8 caracteres
                </li>
                <li className={passwordStrength.uppercase ? 'met' : ''}>
                  ✓ Al menos una mayúscula
                </li>
                <li className={passwordStrength.lowercase ? 'met' : ''}>
                  ✓ Al menos una minúscula
                </li>
                <li className={passwordStrength.number ? 'met' : ''}>
                  ✓ Al menos un número
                </li>
                <li className={passwordStrength.special ? 'met' : ''}>
                  ✓ Al menos un carácter especial
                </li>
              </ul>
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="confirmPassword" className="form-label">
              Confirmar Contraseña
            </label>
            <input
              id="confirmPassword"
              name="confirmPassword"
              type="password"
              required
              className="form-input"
              value={formData.confirmPassword}
              onChange={handleChange}
              disabled={isLoading}
              placeholder="••••••••"
            />
          </div>

          <button
            type="submit"
            className="primary-button"
            disabled={isLoading}
          >
            {isLoading ? (
              <>
                <span className="spinner">⭮</span>
                <span>Registrando...</span>
              </>
            ) : (
              'Registrarse'
            )}
          </button>
        </form>

        <div className="auth-link">
          <p>
            ¿Ya tienes una cuenta?{' '}
            <Link href="/login">
              Inicia sesión
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
